// AUTOGENERATED by exporter.py from SException.java
package pyjvm;

public final class SExceptionClass extends Type {
	private SExceptionClass() {}

	public static final StringDict dict;
	public static final SExceptionClass instance = new SExceptionClass();
	public static final Obj constructor;
	
	static {
		if("SException".equals("NativeObj") || "SException".equals("UserObj"))
			dict = new StringDict();
		else
			dict = NativeObjClass.dict.copy();
		
		constructor = new Obj() {
			public Obj call(Obj[] args)  {
				if(args.length != 1) {
					throw new ScriptError(ScriptError.TypeError, "Bad number of arguments");
				}
				return SException.create(args[0]);
			}
		};
		
	}
	public final StringDict getDict() {
		return dict;
	}
	public final Obj getEntry(int name) {
		return dict.get(name);
	}
	public final Obj call(Obj[] args) {
		if(constructor == null)
			throw new ScriptError(ScriptError.TypeError, "Object uninitializable");
		return constructor.call(args);
	}
}
